name: stock_exchange_holidays
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        python-version: 3.7
        python-version: 3.8
        python-version: 3.9
        python-version: 3.10

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install codecov

    - name: Run lint
      run: |
        make lint

    - name: Run tests and coverage
      run: |
        make test
        codecov